import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import NextSessionProvider from './providers'
import { getServerSession } from 'next-auth'
import { cookies } from 'next/headers';
import { authOptions } from './api/auth/[...nextauth]/route'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  const session = await getServerSession(authOptions);

  return (
    <html lang="en">
      <NextSessionProvider session={session}>
        <body className={inter.className}>
          {children}
        </body>
      </NextSessionProvider>
    </html>
  )
}
